version: "3"

services:
  backend:
    hostname: subscriby
    container_name: subscriby_backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "${COMPOSE_EXPOSED_PORT}:${PROC_BIND_PORT}"
    links:
      - database
    depends_on:
      - database
    build: .
    command: "poetry run gunicorn 'app.app:create_application()' -c gunicorn.conf.py"
  database:
    image: postgres:14-alpine
    hostname: subscriby
    container_name: subscriby_database
    restart: unless-stopped
    env_file: .database.env
    volumes:
      - ../db:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "max_connections=1000"
      - "-c"
      - "shared_buffers=128MB"
